### PR TITLE
Manage secrets encrypted to travis via script

### PR DESCRIPTION
**Pull request by nibalizer**
Also add a list of modules and the encrypted secrets themselves

### CODE REVIEW

**Comment by raphink** [comment]
I'd be in favor of using modulesync and put these things in .sync.yml.

**Comment by igalic** [comment]
same.

**Comment by igalic** [comment]
i also think we should close https://github.com/puppet-community/puppet-community.github.io/issues/5 in favour of this repository.
i've already stated on the docs to puppet-community.github.io that it's only for issues against the community, and we haven't been around long enough to wrong anyone ;)

**Comment by nibalizer** [comment]
@raphink @igalic agree. I don't think that means I should close this PR though since we need a location to stage them before they get pushed out to .sync.yml. When we get a new module (or 7) or rotate the forge password I want to just run a single script with the password, not make 7 prs myself.

**Comment by igalic** [comment]
*nod*

**Comment by nibalizer** [comment]
I'm basically already using this so I'm gonna merge it. We can revert it or replace it in another PR.

**Pull request merged**
